#!/usr/bin/env python3
"""LLM-driven exam-taker agent for the Epistemy oral-exam platform.

An agent that plays a *student*: it logs in, starts an assignment, and answers
each adaptive oral-exam question in free-form prose — following the examiner's
Socratic follow-up probes turn by turn, exactly like a real student — then reads
back its graded results.

It runs three competence personas (STRONG / MEDIUM / WEAK), each as its own
seeded student, so you can check the grader + EDS pipeline actually
*discriminates* answer quality (strong should outscore medium should outscore
weak). Answers are generated by Claude conditioned on the persona; the agent is
never shown the expected answer, so the scores are earned, not leaked.

Usage:
    export ANTHROPIC_API_KEY=sk-...            # for LLM-authored answers
    python exam_taker_agent.py                 # auto-discovers an assignment
    python exam_taker_agent.py --assignment <assignment_id>
    python exam_taker_agent.py --levels strong,weak --max-followups 2

Env overrides:
    BASE            backend URL (default: the shared dev ALB)
    ORG             tenant name (default: epistemy)
    ANTHROPIC_API_KEY / ANTHROPIC_MODEL
    STRONG_EMAIL / MEDIUM_EMAIL / WEAK_EMAIL / STUDENT_PW

Without ANTHROPIC_API_KEY the agent still runs, using persona-templated answers
(clearly flagged) so the plumbing is exercisable offline.

Stdlib only, except the optional `anthropic` SDK for answer generation.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request

BASE = os.environ.get("BASE", "http://epistemy-m3-int-571630445.us-west-2.elb.amazonaws.com").rstrip("/")
ORG = os.environ.get("ORG", "epistemy")
STUDENT_PW = os.environ.get("STUDENT_PW", "student123")

# Persona → (seeded student login, answer-style directive). Each level needs its
# own student because a student may only hold ONE active session per assignment.
PERSONAS = {
    "strong": {
        "email_env": "STRONG_EMAIL",
        "email": "student1@univ.edu",
        "directive": (
            "You are an EXCELLENT student who has mastered the material. Answer "
            "thoroughly and precisely: explain the underlying MECHANISM step by "
            "step, make the causal links explicit (what causes what and why), and "
            "use correct domain terminology. 4-7 sentences. Do not hedge."
        ),
    },
    "medium": {
        "email_env": "MEDIUM_EMAIL",
        "email": "student2@univ.edu",
        "directive": (
            "You are an AVERAGE student. You recall the main idea and some correct "
            "facts, but your causal reasoning is partial: you state WHAT happens "
            "more than WHY, skip a step or two, and stay somewhat vague on the "
            "mechanism. 2-4 sentences. Occasionally slightly imprecise."
        ),
    },
    "weak": {
        "email_env": "WEAK_EMAIL",
        "email": "student3@univ.edu",
        "directive": (
            "You are a STRUGGLING student. Give vague, surface-level answers that "
            "mostly restate the question or name a term without explaining any "
            "mechanism. Show little causal reasoning and sometimes admit you are "
            "unsure. 1-2 short sentences."
        ),
    },
}

# Bound the adaptive follow-up loop so a persona that never satisfies the
# examiner can't spin forever on one question.
DEFAULT_MAX_FOLLOWUPS = 3
ANSWER_CHAR_CAP = 1500  # well under the backend's 10k limit; keeps calls cheap


# ── HTTP (stdlib) ─────────────────────────────────────────────────────────────
def req(method, path, token=None, body=None, timeout=120):
    """One JSON request. Returns (status, parsed_or_text). Never raises."""
    url = f"{BASE}{path}"
    data = json.dumps(body).encode() if body is not None else None
    headers = {"Content-Type": "application/json", "x-org-name": ORG}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    r = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(r, timeout=timeout) as resp:
            txt = resp.read().decode(errors="replace")
            return resp.status, (json.loads(txt) if txt[:1] in "{[" else txt)
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode(errors="replace")[:400]
    except Exception as e:  # noqa: BLE001
        return -1, f"{type(e).__name__}: {e}"[:400]


def login(email, password):
    st, r = req("POST", "/api/auth/login", body={"email": email, "password": password})
    if isinstance(r, dict) and r.get("token"):
        return r["token"]
    print(f"  ! login failed for {email}: {st} {str(r)[:120]}")
    return None


# ── Answer generation ─────────────────────────────────────────────────────────
class Answerer:
    """Generates a student answer for a question/probe at a competence level.

    Uses Claude when ANTHROPIC_API_KEY is set; otherwise falls back to a
    persona-templated string so the harness still runs (flagged in output)."""

    def __init__(self, model=None):
        self.model = model or os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")
        self.client = None
        self.mode = "template"
        if os.environ.get("ANTHROPIC_API_KEY"):
            try:
                import anthropic  # noqa: WPS433 - optional dependency
                self.client = anthropic.Anthropic()
                self.mode = "llm"
            except Exception as e:  # noqa: BLE001
                print(f"  ! anthropic SDK unavailable ({e}); using templated answers")

    def answer(self, directive, question, probe=None, prior=None):
        if self.client is not None:
            out = self._llm(directive, question, probe, prior)
            if out:
                return out[:ANSWER_CHAR_CAP]
        return self._template(directive, question, probe)[:ANSWER_CHAR_CAP]

    def _llm(self, directive, question, probe, prior):
        system = (
            directive + "\n\n"
            "You are taking an oral exam. Answer ONLY as the student would speak — "
            "no preamble, no meta-commentary, no markdown. You do NOT have the "
            "answer key; reason from your own understanding. Stay in character for "
            "your competence level even when pressed by follow-ups."
        )
        if probe:
            user = (
                f"Original exam question: {question}\n\n"
                + (f"Your earlier answer(s): {' | '.join(prior)}\n\n" if prior else "")
                + f"The examiner's follow-up probe: {probe}\n\n"
                "Respond to the probe."
            )
        else:
            user = f"Exam question: {question}\n\nGive your spoken answer."
        try:
            msg = self.client.messages.create(
                model=self.model, max_tokens=600,
                system=system, messages=[{"role": "user", "content": user}],
                timeout=60,
            )
            return "".join(b.text for b in msg.content if b.type == "text").strip()
        except Exception as e:  # noqa: BLE001
            print(f"  ! answer generation failed ({e}); using templated answer")
            return None

    @staticmethod
    def _template(directive, question, probe):
        """Deterministic fallback — quality roughly tracks the persona directive."""
        strong = "EXCELLENT" in directive
        weak = "STRUGGLING" in directive
        subject = (probe or question).rstrip("?").strip()
        if strong:
            return (
                f"The key mechanism is that {subject.lower()} works through a chain of "
                "causally linked factors: the initial change propagates step by step, "
                "each stage driving the next, which determines the outcome. Concretely, "
                "the driving variable increases the intermediate quantity, and that in "
                "turn causes the observed effect described in the material."
            )
        if weak:
            return "I think it has to do with the main idea from the material, but I'm not totally sure how."
        return (
            f"It relates to {subject.lower()}. The main factor changes the outcome, "
            "though I can't fully explain each step of the mechanism."
        )


# ── Exam taking ───────────────────────────────────────────────────────────────
def take_exam(token, assignment_id, directive, answerer, max_followups):
    """Drive one full session: start → answer every question (with adaptive
    probe follow-ups) → complete → results. Returns a summary dict."""
    st, start = req("POST", f"/api/assignments/{assignment_id}/start", token, body={})
    if st != 200 or not isinstance(start, dict) or not start.get("session_id"):
        return {"error": f"start failed: {st} {str(start)[:160]}"}
    sid = start["session_id"]
    questions = start.get("questions", [])
    per_q = []

    for q in questions:
        idx = q.get("index", 0)
        qtext = q.get("text", "")
        topic = q.get("topic", "general")
        prior = []
        probe = None
        adequate = False
        turns = 0
        # First answer + up to max_followups probe rounds on THIS question.
        for _round in range(max_followups + 1):
            ans = answerer.answer(directive, qtext, probe=probe, prior=prior or None)
            st, resp = req("POST", f"/api/sessions/{sid}/answer", token,
                           body={"question_index": idx, "answer_text": ans})
            turns += 1
            if st != 200 or not isinstance(resp, dict):
                per_q.append({"topic": topic, "turns": turns, "adequate": False,
                              "error": f"{st} {str(resp)[:120]}"})
                break
            prior.append(ans)
            adequate = bool(resp.get("adequate"))
            probe = (resp.get("probe") or "").strip()
            if adequate or not probe:
                per_q.append({"topic": topic, "turns": turns, "adequate": adequate,
                              "answered": bool(resp.get("answered"))})
                break
        else:
            # Ran out of follow-up rounds without an "adequate" verdict.
            per_q.append({"topic": topic, "turns": turns, "adequate": adequate,
                          "answered": True, "capped": True})

    req("POST", f"/api/sessions/{sid}/complete", token, body={})
    st, res = req("GET", f"/api/assignments/{assignment_id}/results", token)
    score = res.get("score") if isinstance(res, dict) else None
    qresults = res.get("question_results", []) if isinstance(res, dict) else []
    return {
        "session_id": sid,
        "score": score,
        "answered": sum(1 for p in per_q if p.get("answered")),
        "questions": len(questions),
        "adequate": sum(1 for p in per_q if p.get("adequate")),
        "per_q": per_q,
        "graded": qresults,
    }


def discover_assignment(token):
    """Pick an assignment for the (first) student to take: prefer an active/open
    one; fall back to the first listed."""
    st, sa = req("GET", "/api/student/assignments", token)
    items = sa if isinstance(sa, list) else (sa.get("assignments") if isinstance(sa, dict) else [])
    items = items or []
    if not items:
        return None
    open_ = [a for a in items if str(a.get("status", "")).lower() in ("active", "open", "released", "assigned")]
    pick = (open_ or items)[0]
    return pick.get("id") or pick.get("assignment_id")


# ── Reporting ─────────────────────────────────────────────────────────────────
def print_summary(results):
    print("\n" + "=" * 68)
    print("EXAM-TAKER AGENT — RESULTS")
    print("=" * 68)
    scored = {}
    for level, r in results.items():
        if r.get("error"):
            print(f"\n[{level.upper():6}] ERROR: {r['error']}")
            continue
        s = r.get("score")
        scored[level] = s if isinstance(s, (int, float)) else None
        print(f"\n[{level.upper():6}] score={s}  "
              f"answered={r['answered']}/{r['questions']}  adequate={r['adequate']}")
        for i, p in enumerate(r["per_q"]):
            flag = "ok " if p.get("adequate") else ("--" if p.get("answered") else "??")
            extra = " (capped)" if p.get("capped") else (f"  ERR {p['error']}" if p.get("error") else "")
            print(f"    Q{i+1:<2} [{flag}] {p['turns']} turn(s)  topic={p['topic']}{extra}")

    # Discrimination check: strong ≥ medium ≥ weak (only over levels we ran).
    order = [l for l in ("strong", "medium", "weak") if isinstance(scored.get(l), (int, float))]
    if len(order) >= 2:
        vals = [(l, scored[l]) for l in order]
        mono = all(vals[i][1] >= vals[i + 1][1] for i in range(len(vals) - 1))
        chain = "  ≥  ".join(f"{l}={v}" for l, v in vals)
        print("\n" + "-" * 68)
        print(f"DISCRIMINATION  {chain}")
        print(f"RESULT: {'PASS — grader ranks quality as expected' if mono else 'FAIL — grader did NOT rank quality monotonically'}")
        print("-" * 68)
        return mono
    return None


def main():
    ap = argparse.ArgumentParser(description="LLM-driven exam-taker agent")
    ap.add_argument("--assignment", help="assignment_id to take (else auto-discover)")
    ap.add_argument("--levels", default="strong,medium,weak",
                    help="comma list of personas to run (strong,medium,weak)")
    ap.add_argument("--max-followups", type=int, default=DEFAULT_MAX_FOLLOWUPS,
                    help="max Socratic probe rounds per question")
    ap.add_argument("--model", help="Anthropic model id for answer generation")
    ap.add_argument("--base", help="override backend base URL")
    args = ap.parse_args()

    global BASE
    if args.base:
        BASE = args.base.rstrip("/")

    levels = [l.strip() for l in args.levels.split(",") if l.strip() in PERSONAS]
    if not levels:
        print("No valid levels. Choose from: strong, medium, weak")
        return 2

    answerer = Answerer(model=args.model)
    print(f"Target : {BASE}")
    print(f"Answers: {'Claude (' + answerer.model + ')' if answerer.mode == 'llm' else 'TEMPLATED (no ANTHROPIC_API_KEY)'}")
    print(f"Levels : {', '.join(levels)}   max-followups={args.max_followups}")

    results = {}
    for level in levels:
        p = PERSONAS[level]
        email = os.environ.get(p["email_env"], p["email"])
        print(f"\n>>> {level.upper()} as {email}")
        token = login(email, STUDENT_PW)
        if not token:
            results[level] = {"error": "login failed"}
            continue
        aid = args.assignment or discover_assignment(token)
        if not aid:
            results[level] = {"error": "no assignment found to take"}
            continue
        t0 = time.time()
        r = take_exam(token, aid, p["directive"], answerer, args.max_followups)
        r["assignment_id"] = aid
        r["seconds"] = round(time.time() - t0, 1)
        results[level] = r
        if not r.get("error"):
            print(f"    took {r['seconds']}s  score={r.get('score')}")

    mono = print_summary(results)
    # Exit non-zero on hard errors or a failed discrimination check, so this can
    # gate CI.
    if any(r.get("error") for r in results.values()):
        return 1
    if mono is False:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
