"""Repository protocol shared by the in-memory and Postgres stores."""
from __future__ import annotations
from typing import Protocol, Optional, List

from epistemy_m3.models import Material, MaterialVersion, Chunk, AsyncJob, Org, Course


class Repository(Protocol):
    """Persistence surface for M3 domain rows. RLS is set per call."""

    def set_tenant(self, org_id: str) -> None: ...

    def get_or_create_org(self, org_name: str) -> Org: ...
    def get_or_create_course(self, org_id: str, course_name: str) -> Course: ...
    def get_course(self, course_id: str) -> Optional[Course]: ...

    def create_material(self, material: Material) -> Material: ...
    def get_material(self, material_id: str) -> Optional[Material]: ...
    def list_materials(self, course_id: str) -> List[Material]: ...
    def set_current_version(self, material_id: str, version_id: str) -> None: ...

    def create_version(self, version: MaterialVersion) -> MaterialVersion: ...
    def get_version(self, version_id: str) -> Optional[MaterialVersion]: ...
    def list_versions(self, material_id: str) -> List[MaterialVersion]: ...
    def max_version_no(self, material_id: str) -> int: ...
    def update_version_status(self, version_id: str, status, error=None) -> None: ...

    def upsert_chunks(self, chunks: List[Chunk]) -> int: ...
    def count_chunks(self, version_id: str) -> int: ...

    def create_job(self, job: AsyncJob) -> AsyncJob: ...
    def update_job(self, job_id: str, status=None, step_name=None,
                   progress_pct=None, error=None) -> None: ...
    def get_job(self, job_id: str) -> Optional[AsyncJob]: ...
