import { jsPDF } from 'jspdf';
import type { ExamResult } from './api/exam';

// One question and the exchange that followed it. `score` is optional on
// purpose: a student's grade may be unreleased, and the PDF must not leak the
// draft EDS any more than the screen does.
export interface TranscriptEntry {
  n: number;
  topic?: string;
  question: string;
  attempted?: boolean;
  score?: number | null;
  exchange: { who: string; text: string }[];
}

export interface TranscriptMeta {
  heading: string;
  totalQuestions: number;
  answered: number;
  score?: number | null;
  lines?: string[];          // extra metadata rows, e.g. 'Completed: ...'
}

const NAVY = '#1B2A4A';
const GOLD = '#9B7530';
const GRAY = '#6B6355';
const BLACK = '#333333';

export function downloadTranscriptPdf(meta: TranscriptMeta, entries: TranscriptEntry[]): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  function checkPageBreak(needed: number) {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      y = margin;
    }
  }

  function addFooters() {
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(GRAY);
      doc.text(`Page ${i} of ${totalPages}`, margin, pageHeight - 10);
      doc.text('Generated by Epistemy', pageWidth - margin, pageHeight - 10, { align: 'right' });
    }
  }

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(NAVY);
  doc.text(meta.heading, margin, y);
  y += 10;

  doc.setDrawColor(GOLD);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(GRAY);
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const rows = [
    `Date: ${dateStr}`,
    `Total Questions: ${meta.totalQuestions}`,
    `Questions Answered: ${meta.answered} of ${meta.totalQuestions}`,
    ...(meta.lines || []),
  ];
  if (meta.score != null) rows.push(`Overall EDS Score: ${Math.round(meta.score)}`);
  rows.forEach((r) => {
    doc.text(r, margin, y);
    y += 5;
  });
  y += 7;

  entries.forEach((t) => {
    checkPageBreak(40);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(NAVY);
    doc.text(t.topic ? `Question ${t.n} — ${t.topic}` : `Question ${t.n}`, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(BLACK);
    doc.splitTextToSize(t.question, contentWidth).forEach((line: string) => {
      checkPageBreak(6);
      doc.text(line, margin, y);
      y += 5;
    });
    y += 3;

    if (t.exchange.length === 0) {
      checkPageBreak(6);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(GRAY);
      doc.text('(Skipped, no response)', margin + 5, y);
      y += 6;
    } else {
      t.exchange.forEach((e) => {
        checkPageBreak(10);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(e.who === 'Student' ? '#2563eb' : NAVY);
        doc.text(`${e.who}:`, margin + 5, y);
        y += 4;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(BLACK);
        doc.splitTextToSize(e.text, contentWidth - 10).forEach((line: string) => {
          checkPageBreak(5);
          doc.text(line, margin + 10, y);
          y += 4;
        });
        y += 3;
      });
    }

    // Footer line per question — omitted entirely when there is no score to show.
    const bits: string[] = [];
    if (t.score != null) bits.push(`Score: +${Math.round(t.score)} EDS`);
    if (t.attempted !== undefined) bits.push(t.attempted ? 'Answered' : 'Skipped');
    if (bits.length) {
      checkPageBreak(8);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(GRAY);
      doc.text(bits.join('  •  '), margin, y);
      y += 6;
    }

    checkPageBreak(6);
    doc.setDrawColor('#E5E5E5');
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;
  });

  addFooters();
  doc.save(`Epistemy_Transcript_${new Date().toISOString().slice(0, 10)}.pdf`);
}

// Post-submission transcript inside the exam. `showDraftScores` is false on a
// graded item, which strips the EDS and the evaluator's turns so this matches the
// Results page — the in-app score is a draft until the professor releases it.
export function examTranscript(
  questions: { topic?: string; text: string }[],
  qData: { attempted: boolean; score: number; turns: { role: string; text: string }[] }[],
  opts: { showDraftScores: boolean; overallScore: number; answered: number },
): { meta: TranscriptMeta; entries: TranscriptEntry[] } {
  const entries = qData.map((q, i) => ({
    n: i + 1,
    topic: questions[i]?.topic || '',
    question: questions[i]?.text || '',
    attempted: q.attempted,
    // q.score is 0..1 in the exam; the transcript speaks the 0-100 EDS the rest
    // of the app shows (it used to print Math.round(0.8) = 1).
    score: opts.showDraftScores ? Math.round(q.score * 100) : null,
    // turns[0] is the question itself, already carried by `question`.
    exchange: q.turns
      .slice(1)
      .filter((t) => opts.showDraftScores || t.role === 'student')
      .map((t) => ({ who: t.role === 'student' ? 'Student' : 'Evaluator', text: t.text })),
  }));
  return {
    meta: {
      heading: 'Epistemy — Exam Transcript',
      totalQuestions: questions.length,
      answered: opts.answered,
      score: opts.showDraftScores ? opts.overallScore : null,
    },
    entries,
  };
}

// Results-page transcript: the student's own answers plus any released feedback.
// Scores ride along only when the API sent them (i.e. the grade is released).
export function resultsTranscript(data: ExamResult): { meta: TranscriptMeta; entries: TranscriptEntry[] } {
  const entries = (data.question_results || []).map((q, i) => ({
    n: i + 1,
    question: q.question_text,
    score: q.score ?? null,
    exchange: [
      ...(q.answer ? [{ who: 'Student', text: q.answer }] : []),
      ...(q.feedback ? [{ who: 'Evaluator', text: q.feedback }] : []),
    ],
  }));
  const meta: TranscriptMeta = {
    heading: 'Epistemy — Results Transcript',
    totalQuestions: data.total_questions,
    answered: data.questions_answered,
    score: data.score,
    lines: data.completed_at
      ? [`Completed: ${new Date(data.completed_at).toLocaleString('en-US')}`]
      : [],
  };
  return { meta, entries };
}
